pool: 'default'

variables:
  node.version: '20.x'
  projectRoot: '.'

steps:
  - task: NodeTool@0
    displayName: 'Use Node.js $(node.version)'
    inputs:
      versionSpec: '$(node.version)'

  - script: |
      npm install
    workingDirectory: $(projectRoot)
    displayName: "Install dependencies"
  
  - script: |
      npm run build
    workingDirectory: $(projectRoot)
    displayName: "Build project"
  
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(projectRoot)/dist'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true
  
  - task: AzureWebApp@1
    displayName: 'Deploy Azure Web App'
    inputs:
      azureSubscription: 'web-warriors-service-connection'
      appType: 'webAppLinux'
      appName: "atc-2024-webwarriors-fe-linux-web-app"
      package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      startUpCommand: 'pm2 serve /home/site/wwwroot --no-daemon'
